In [120]:
import os
from sqlalchemy import create_engine, text
from dotenv import load_dotenv
import pandas as pd

def connect_to_database():
    DATABASE_URL = (
        "postgresql://postgres:1234"
        "@localhost:5432/google_and_spotify"
    )

    engine = create_engine(
        DATABASE_URL
    )
    return engine

In [121]:
engine = connect_to_database()

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print(result.scalar())

1

In [122]:
df_tracks = pd.read_sql(
    "SELECT * FROM track_audio_features",
    engine
)
df_tracks.head()

,feature_id,track_id,provider,provider_track_id,provider_href,provider_isrc,acousticness,danceability,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,raw_response,fetched_at,popularity
0,1,1,reccobeats,49db08f5-e4e2-4238-8f02-ba897fdbcc81,https://open.spotify.com/track/3D7izPzeEcz7lBh...,USUM71308530,0.00392,0.503,0.858,0.000000,5.0,0.119,-6.270,0.0,0.0578,121.007,0.361,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.443682,NaN
1,2,2,reccobeats,57a17de6-a2bb-421e-a496-19d977e24105,https://open.spotify.com/track/3WKYPmiPpJas9j5...,USUM71309545,0.16000,0.645,0.736,0.000156,9.0,0.600,-6.862,0.0,0.0514,115.030,0.347,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.455670,NaN
2,3,3,reccobeats,ab047604-e433-492a-8d93-0b692e1ce545,https://open.spotify.com/track/4pHQ9RYFhn3W0ha...,USUM71310343,0.15900,0.642,0.792,0.000553,11.0,0.305,-6.799,0.0,0.0688,114.960,0.623,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.461060,NaN
3,4,4,reccobeats,c1f72307-6058-4b1a-9b2d-acbc7af12958,https://open.spotify.com/track/2vXKRlJBXyOcvZY...,USQX91803314,0.09280,0.658,0.671,0.000919,2.0,0.115,-12.210,1.0,0.0364,100.967,0.165,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.464330,NaN
4,5,5,reccobeats,c879d5fb-ef67-4ec5-823e-198683f88ce8,https://open.spotify.com/track/0V4l4GQhgnWQGtC...,USCM51100546,0.22700,0.418,0.546,0.000000,0.0,0.229,-9.057,0.0,0.2380,160.152,0.294,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.467397,NaN

In [123]:
df_tracks.shape

(3481, 20)

In [124]:
df_fact_listening = pd.read_sql(
    "SELECT * FROM fact_listening",
    engine
)
df_fact_listening.head()

,listening_id,track_id,timestamp_utc,timestamp_uts,track_url
0,1,1,2025-01-24 18:52:17,1737755537,https://www.last.fm/music/Billie+Eilish/_/WILD...
1,2,2,2025-01-24 18:46:23,1737755183,https://www.last.fm/music/The+Neighbourhood/_/...
2,3,3,2025-01-24 18:42:32,1737754952,https://www.last.fm/music/Drake/_/9
3,4,4,2025-01-24 18:39:35,1737754775,https://www.last.fm/music/Drake/_/Make+Me+Proud
4,5,5,2025-01-24 18:34:21,1737754461,https://www.last.fm/music/The+Weeknd/_/Wicked+...

In [125]:
df_fact_listening.shape

(26940, 5)

In [126]:
df_tracks_fact_listening = df_fact_listening.merge(
    df_tracks,
    on="track_id",
    how="left",
    suffixes=("_listening", "_track")
)

df_tracks_fact_listening.head()

,listening_id,track_id,timestamp_utc,timestamp_uts,track_url,feature_id,provider,provider_track_id,provider_href,provider_isrc,...,key,liveness,loudness,mode,speechiness,tempo,valence,raw_response,fetched_at,popularity
0,1,1,2025-01-24 18:52:17,1737755537,https://www.last.fm/music/Billie+Eilish/_/WILD...,1.0,reccobeats,49db08f5-e4e2-4238-8f02-ba897fdbcc81,https://open.spotify.com/track/3D7izPzeEcz7lBh...,USUM71308530,...,5.0,0.119,-6.270,0.0,0.0578,121.007,0.361,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.443682,NaN
1,2,2,2025-01-24 18:46:23,1737755183,https://www.last.fm/music/The+Neighbourhood/_/...,2.0,reccobeats,57a17de6-a2bb-421e-a496-19d977e24105,https://open.spotify.com/track/3WKYPmiPpJas9j5...,USUM71309545,...,9.0,0.600,-6.862,0.0,0.0514,115.030,0.347,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.455670,NaN
2,3,3,2025-01-24 18:42:32,1737754952,https://www.last.fm/music/Drake/_/9,3.0,reccobeats,ab047604-e433-492a-8d93-0b692e1ce545,https://open.spotify.com/track/4pHQ9RYFhn3W0ha...,USUM71310343,...,11.0,0.305,-6.799,0.0,0.0688,114.960,0.623,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.461060,NaN
3,4,4,2025-01-24 18:39:35,1737754775,https://www.last.fm/music/Drake/_/Make+Me+Proud,4.0,reccobeats,c1f72307-6058-4b1a-9b2d-acbc7af12958,https://open.spotify.com/track/2vXKRlJBXyOcvZY...,USQX91803314,...,2.0,0.115,-12.210,1.0,0.0364,100.967,0.165,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.464330,NaN
4,5,5,2025-01-24 18:34:21,1737754461,https://www.last.fm/music/The+Weeknd/_/Wicked+...,5.0,reccobeats,c879d5fb-ef67-4ec5-823e-198683f88ce8,https://open.spotify.com/track/0V4l4GQhgnWQGtC...,USCM51100546,...,0.0,0.229,-9.057,0.0,0.2380,160.152,0.294,"{'search': {'page': 0, 'size': 25, 'content': ...",2026-08-26 19:59:18.467397,NaN

In [127]:
audio_features = [
    "acousticness",
    "danceability",
    "energy",
    "instrumentalness",
    "key",
    "liveness",
    "loudness",
    "mode",
    "speechiness",
    "tempo",
    "valence",
    "popularity",
]

# base de features por track
tracks_model = (
    df_tracks
    .drop_duplicates(subset=["track_id"])
    .loc[:, ["track_id"] + audio_features]
    .fillna(0)
)

# quantidade de streams por track
streams_por_track = (
    df_fact_listening
    .groupby("track_id", as_index=False)
    .agg(quantidade_streams=("listening_id", "count"))
)

# dataframe final para treino
# keep: track_id, quantidade_streams + audio features
# opcional: target binário para gostar/nao gostar
# gosto = 1 quando a música teve pelo menos 1 stream

df_model = tracks_model.merge(streams_por_track, on="track_id", how="left")

df_model["quantidade_streams"] = df_model["quantidade_streams"].fillna(0).astype(int)
df_model["gostei"] = (df_model["quantidade_streams"] > 0).astype(int)

# ordem final das colunas
cols = ["track_id", "quantidade_streams"] + audio_features + ["gostei"]
df_model = df_model[cols]

df_model.head()

,track_id,quantidade_streams,acousticness,danceability,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,popularity,gostei
0,1,94,0.00392,0.503,0.858,0.000000,5.0,0.119,-6.270,0.0,0.0578,121.007,0.361,0.0,1
1,2,69,0.16000,0.645,0.736,0.000156,9.0,0.600,-6.862,0.0,0.0514,115.030,0.347,0.0,1
2,3,157,0.15900,0.642,0.792,0.000553,11.0,0.305,-6.799,0.0,0.0688,114.960,0.623,0.0,1
3,4,51,0.09280,0.658,0.671,0.000919,2.0,0.115,-12.210,1.0,0.0364,100.967,0.165,0.0,1
4,5,98,0.22700,0.418,0.546,0.000000,0.0,0.229,-9.057,0.0,0.2380,160.152,0.294,0.0,1

In [128]:
df_model

,track_id,quantidade_streams,acousticness,danceability,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,popularity,gostei
0,1,94,0.00392,0.503,0.858,0.000000,5.0,0.1190,-6.270,0.0,0.0578,121.007,0.361,0.0,1
1,2,69,0.16000,0.645,0.736,0.000156,9.0,0.6000,-6.862,0.0,0.0514,115.030,0.347,0.0,1
2,3,157,0.15900,0.642,0.792,0.000553,11.0,0.3050,-6.799,0.0,0.0688,114.960,0.623,0.0,1
3,4,51,0.09280,0.658,0.671,0.000919,2.0,0.1150,-12.210,1.0,0.0364,100.967,0.165,0.0,1
4,5,98,0.22700,0.418,0.546,0.000000,0.0,0.2290,-9.057,0.0,0.2380,160.152,0.294,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476,2719,1,0.27100,0.812,0.496,0.000000,9.0,0.0955,-5.969,0.0,0.2970,109.979,0.550,73.0,1
3477,2726,1,0.64500,0.482,0.512,0.000076,1.0,0.1050,-9.410,0.0,0.1570,89.284,0.584,52.0,1
3478,2747,1,0.22500,0.724,0.531,0.000000,5.0,0.1100,-4.108,0.0,0.2980,89.901,0.141,57.0,1
3479,2771,3,0.16800,0.545,0.476,0.000000,7.0,0.1300,-7.444,0.0,0.2840,154.362,0.223,57.0,1
3480,2779,1,0.00746,0.615,0.702,0.004310,7.0,0.0608,-9.686,1.0,0.0278,96.987,0.734,66.0,1

In [129]:
import numpy as np

df_model["gostei"] = np.where(
    df_model["quantidade_streams"] > 10,
    1,
    0
)

In [130]:
df_model

,track_id,quantidade_streams,acousticness,danceability,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,popularity,gostei
0,1,94,0.00392,0.503,0.858,0.000000,5.0,0.1190,-6.270,0.0,0.0578,121.007,0.361,0.0,1
1,2,69,0.16000,0.645,0.736,0.000156,9.0,0.6000,-6.862,0.0,0.0514,115.030,0.347,0.0,1
2,3,157,0.15900,0.642,0.792,0.000553,11.0,0.3050,-6.799,0.0,0.0688,114.960,0.623,0.0,1
3,4,51,0.09280,0.658,0.671,0.000919,2.0,0.1150,-12.210,1.0,0.0364,100.967,0.165,0.0,1
4,5,98,0.22700,0.418,0.546,0.000000,0.0,0.2290,-9.057,0.0,0.2380,160.152,0.294,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476,2719,1,0.27100,0.812,0.496,0.000000,9.0,0.0955,-5.969,0.0,0.2970,109.979,0.550,73.0,0
3477,2726,1,0.64500,0.482,0.512,0.000076,1.0,0.1050,-9.410,0.0,0.1570,89.284,0.584,52.0,0
3478,2747,1,0.22500,0.724,0.531,0.000000,5.0,0.1100,-4.108,0.0,0.2980,89.901,0.141,57.0,0
3479,2771,3,0.16800,0.545,0.476,0.000000,7.0,0.1300,-7.444,0.0,0.2840,154.362,0.223,57.0,0
3480,2779,1,0.00746,0.615,0.702,0.004310,7.0,0.0608,-9.686,1.0,0.0278,96.987,0.734,66.0,0

In [131]:
artist_track = pd.read_sql(
    "SELECT track_id, artist_name FROM dim_track",
    engine
)

df_model = df_model.merge(
    artist_track,
    on="track_id",
    how="left"
)

df_model = df_model[
    ["track_id", "artist_name", "quantidade_streams"] + audio_features + ["gostei"]
]

df_model.head()

,track_id,artist_name,quantidade_streams,acousticness,danceability,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,valence,popularity,gostei
0,1,The Weeknd,94,0.00392,0.503,0.858,0.000000,5.0,0.119,-6.270,0.0,0.0578,121.007,0.361,0.0,1
1,2,The Weeknd,69,0.16000,0.645,0.736,0.000156,9.0,0.600,-6.862,0.0,0.0514,115.030,0.347,0.0,1
2,3,The Weeknd,157,0.15900,0.642,0.792,0.000553,11.0,0.305,-6.799,0.0,0.0688,114.960,0.623,0.0,1
3,4,Gesaffelstein,51,0.09280,0.658,0.671,0.000919,2.0,0.115,-12.210,1.0,0.0364,100.967,0.165,0.0,1
4,5,Drake,98,0.22700,0.418,0.546,0.000000,0.0,0.229,-9.057,0.0,0.2380,160.152,0.294,0.0,1

In [132]:
df_model.value_counts("gostei")

gostei
0    2836
1     645
Name: count, dtype: int64

In [133]:
df_model = df_model.drop("quantidade_streams", axis=1)

In [134]:
from sklearn.model_selection import train_test_split

X = df_model.drop("gostei", axis=1)
y = df_model["gostei"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [135]:
y_test.value_counts()

gostei
0    562
1    135
Name: count, dtype: int64

In [136]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    random_seed=42,
    verbose=False
)

model.fit(X_train, y_train, cat_features=["artist_name"])

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.05, random_seed=42, verbose=False)

In [137]:
model.score(X_test, y_test)

np.float64(0.8565279770444764)

In [138]:
y_test

3100    0
2912    0
2662    0
2214    0
874     0
       ..
3095    0
152     1
2607    0
2128    1
1027    0
Name: gostei, Length: 697, dtype: int64

In [139]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

y_pred = model.predict(X_test).flatten()

print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score:  {f1_score(y_test, y_pred):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy:  0.8565
Precision: 0.6882
Recall:    0.4741
F1 Score:  0.5614

Confusion Matrix:
[[533  29]
 [ 71  64]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.95      0.91       562
           1       0.69      0.47      0.56       135

    accuracy                           0.86       697
   macro avg       0.79      0.71      0.74       697
weighted avg       0.84      0.86      0.85       697

In [141]:
from sklearn.dummy import DummyClassifier

dummy = DummyClassifier(strategy="most_frequent")
dummy.fit(X_train, y_train)

print(dummy.score(X_test, y_test))

0.806312769010043

In [144]:
model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    random_seed=42,
    verbose=False,
    class_weights=[1, 3]
)

In [143]:
model.fit(
    X_train,
    y_train,
    cat_features=["artist_name"]
)

y_pred = model.predict(X_test).flatten()

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.93      0.91       562
           1       0.65      0.55      0.59       135

    accuracy                           0.86       697
   macro avg       0.77      0.74      0.75       697
weighted avg       0.85      0.86      0.85       697

In [145]:
model.fit(
    X_train,
    y_train,
    cat_features=["artist_name"]
)

y_pred = model.predict(X_test).flatten()

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.92      0.91       562
           1       0.63      0.59      0.61       135

    accuracy                           0.85       697
   macro avg       0.76      0.75      0.76       697
weighted avg       0.85      0.85      0.85       697

In [146]:
y_proba = model.predict_proba(X_test)[:, 1]

for threshold in [0.3, 0.35, 0.4, 0.45, 0.5]:
    y_pred = (y_proba >= threshold).astype(int)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print(
        f"Threshold={threshold:.2f} | "
        f"Precision={precision:.3f} | "
        f"Recall={recall:.3f} | "
        f"F1={f1:.3f}"
    )

Threshold=0.30 | Precision=0.561 | Recall=0.785 | F1=0.654
Threshold=0.35 | Precision=0.582 | Recall=0.733 | F1=0.649
Threshold=0.40 | Precision=0.608 | Recall=0.689 | F1=0.646
Threshold=0.45 | Precision=0.627 | Recall=0.622 | F1=0.625
Threshold=0.50 | Precision=0.627 | Recall=0.585 | F1=0.605